---
pve_nodes:
  hosts:
    pve.home.lab:

docker_swarm_nodes:
  children:
    managers:
      hosts:
        192.168.100.10:
    workers:
      hosts:
        192.168.100.11:
        192.168.100.12:

nfs_server_nodes:
  hosts:
    192.168.100.13:

kube_nodes:
  children:
    cplane:
      hosts:
        kube01.home.lab:
        kube02.home.lab:
    workers:
      hosts:
        kube03.home.lab:
        kube04.home.lab:
        kube05.home.lab:
