---

pve_nodes:
  hosts:
    pve.home.lab:

docker_swarm_nodes:
  children:
    managers:
      hosts:
        192.168.100.10:
    workers:
      hosts:
        192.168.100.11:
        192.168.100.12:

nfs_server_nodes:
  hosts:
    192.168.100.13: