---
- name: Kube dependencies
  hosts: kube_nodes
  #gather_facts: false
  become: true
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.bridge.bridge-nf-call-ip6tables: 1
      net.bridge.bridge-nf-call-iptables: 1
# install dependencies and make some OS settings
  tasks:
  - name: Install dep packages
    ansible.builtin.apt:
      name:
        - curl
        - wget
        - gnupg
        - sudo
        - iptables
        - tmux
        - keepalived
        - haproxy
      state: present
      update_cache: true

  - name: Systemctl config
    ansible.posix.sysctl:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
      sysctl_set: true
      state: present
      reload: true
    loop: "{{ sysctl_config | dict2items }}"