---
- name: Clone Ubuntu template
  community.general.proxmox_kvm:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: "{{ proxmox_node }}"
    clone: "{{ clone_vm }}"
    name: "{{ vm_name }}"
    full: true
    storage: "{{ vm_storage }}"
  register: state

- name: Modifay VM
  community.general.proxmox_kvm:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: "{{ proxmox_node }}"
    vmid: " {{ state.vmid }}"
    memory: "{{ vm_memory }}"
    cores: "{{ vm_cores }}"
    ipconfig:
      ipconfig0: "{{ vm_net }}"
    update: yes
  when: state.changed


- name: Start VM
  community.general.proxmox_kvm:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: "{{ proxmox_node }}"
    name: "{{ vm_name }}"
    vmid: " {{ state.vmid }}"
    state: started
  when: state.changed