---
- name: print etcd info
  ansible.builtin.debug:
    msg: "This task installs etcd cluster"
  tags:
    - etcd

- name: Install dependeces
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Download and unarchive etcd distro
  ansible.builtin.unarchive:
    src: "{{ etcd_archive }}"
    dest: /tmp
    remote_src: yes
    extra_opts: [--strip-components=1]
  tags:
    - etcd

- name: Copy etcd and etcdctl to /usr/local/bin
  ansible.builtin.copy:
    remote_src: yes
    src: "/tmp/{{ item }}"
    dest: /usr/local/bin
    mode: u+x,g+x,o+x
  loop: 
    - etcd
    - etcdctl

- name: Ensure group etcd exists
  ansible.builtin.group:
    name: etcd
    state: present
    system: true

- name: Create etcd user
  ansible.builtin.user:
    name: etcd
    shell: /sbin/nologin
    group: etcd
    system: true

- name: Create directories for etcd
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: etcd
    group: etcd
  loop:
    - /etc/etcd
    - /var/lib/etcd

- name: Copy etcd config
  ansible.builtin.template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    owner: etcd
    group: etcd
    mode: 0640

- name: Copy etcd systemd service config
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: etcd
    group: etcd
    mode: 0640

- name: Enable and start etcd service
  ansible.builtin.systemd:
    daemon_reload: true
    name: etcd
    enabled: true
    state: started
