---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cashe: true
  loop:
    - ca-certificates 
    - curl

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    #file: /etc/apt/keyrings/docker.asc
    state: present

- name: Add the repository to Apt sources
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

-name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cashe: true
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Ensure docker engine is active
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

