---
# tasks file for docker-swarm

- name: Docker Swarm init
  community.docker.docker_swarm:
    state: present
  register: swarm_token
  when: inventory_hostname in groups['managers'][0]

- name: Docker Swarm worker node join
  community.docker.docker_swarm:
    state: join
    remote_addrs: "{{ groups['managers'][0] }}"
    join_token: "{{ hostvars[groups['managers'][0]]['swarm_token']['swarm_facts']['JoinTokens']['Worker'] }}"
  when: inventory_hostname in groups['workers']

