---
- name: Clone Ubuntu template
  community.general.proxmox_kvm:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: "{{ proxmox_node }}"
    clone: "{{ clone_vm }}"
    name: "{{ item.vm_name }}"
    newid: "{{ item.vm_vmid }}"
    full: true
    storage: "{{ vm_storage }}"
  loop: "{{ VMs }}"
  register: state

- name: Modifay VM
  community.general.proxmox_kvm:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: "{{ proxmox_node }}"
    name: "{{ item.vm_name }}"
    vmid: "{{ item.vm_vmid }}"
    memory: "{{ item.vm_memory }}"
    cores: "{{ item.vm_cores }}"
    ipconfig:
      ipconfig0: "{{ item.vm_adapter }}"
    nameservers: "{{ item.vm_nameservers }}"
    searchdomains: "{{ vm_searchdomains }}"
    update: yes
  loop: "{{ VMs }}"
  when: state.changed

# This task is unfortunately neccesary for me. It's not a best way to do that. But I can't change vlan from the Modifay VM task due to proxmox bag. I haven't resolved it yet. 
- name: Modify VM vlan
  ansible.builtin.command: "qm set {{ item.vm_vmid }} -net0 'virtio,bridge=vmbr0,tag={{ item.vm_vlan }}'"
  loop: "{{ VMs }}"

- name: Start VM
  community.general.proxmox_kvm:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: "{{ proxmox_node }}"
    name: "{{ item.vm_name }}"
    vmid: "{{ item.vm_vmid }}"
    state: started
  loop: "{{ VMs }}"
  when: state.changed